# --- Topic ---
lidar_topic: "/lastcloud"
uwb_topic:   "/seed_pose"
imu_topic:   "/vn100/imu"

# --- Manager Logic ---
liteloamNum: 10
shutdown_on_success: true

# --- ICP & Optimization ---
leafCoarse: 0.4
leafFine: 0.2
maxcorrCoarse: 15.0
maxcorrFine: 5.0
iterCoarse: 10
iterFine: 10
icpThresh: 1.5

yaw_step_first: 60.0
fine_enable: true 

# --- Worker Logic ---
icpOnly: false
terminate_after_publish: true

# --- IMU Configuration ---
imu_type: 2
gravity_z: 9.82

# --- Adaptive Downsampling ---
max_lidar_factor: 6000    
ds_radius: 0.4           
min_leaf_size: 0.1