# --- Topic ---
lidar_topic: "/lastcloud"
seed_pose_topic:   "/seed_pose"
imu_topic:   "/vn100/imu"

# --- Manager Logic ---
liteloamNum: 10
shutdown_on_success: true

# --- ICP & Optimization ---
leafCoarse: 0.4
leafFine: 0.2
maxcorrCoarse: 10.0
maxcorrFine: 2.0
iterCoarse: 5
iterFine: 5
icpThresh: 1.5

yaw_step_first: 45.0
fine_enable: false 

# --- Worker Logic ---
icpOnly: false
terminate_after_publish: false

# --- IMU Configuration ---
imu_type: 2
gravity_z: 9.82

# --- Adaptive Downsampling ---
max_lidar_factor: 6000    
ds_radius: 0.4           
min_leaf_size: 0.1